#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
pdfplumber 财报解析 demo · Phase 0 §5 #3 落地项
==================================================

对应项目开发计划 §5 Phase 0 第 3 项:跑通 pdfplumber 财报解析 demo,
评估三大表抽取准确率。本脚本是**最小可跑版本**,目标是用 1 个
固定输入(本地 PDF)跑出结构化 JSON 输出,作为 Phase 0 第一落地项
的可入库起点。

两种用法:
  1) 默认 / --make-sample
     自动生成 1 份"模拟年报"PDF(纯文本 + 1 张示意表),然后
     用 pdfplumber 抽取,JSON 写到 samples/demo-extract.json。
     用于在没有真实 PDF 的情况下验证流程跑通。

  2) --extract <pdf_path>
     抽取任意已有 PDF(支持相对/绝对路径),JSON 写到
     samples/<basename>.extract.json。

输出 JSON 结构(稳定契约,Phase 1 财报速读会沿用):
  {
    "source": "<pdf 路径>",
    "page_count": N,
    "pages": [
      {
        "page_no": 1,
        "text": "...",
        "tables": [
          {"table_no": 1, "rows": [["科目", "金额(亿元)"], ["营业收入", "3867.5"], ...]},
          ...
        ]
      },
      ...
    ]
  }

依赖(已写入 requirements.txt):
  - pdfplumber >= 0.11
  - fpdf2 >= 2.8 (仅 --make-sample 模式需要)
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import pdfplumber

REPO_ROOT = Path(__file__).resolve().parents[1]
SAMPLES_DIR = REPO_ROOT / "samples"
SAMPLES_DIR.mkdir(parents=True, exist_ok=True)


# ---------- 抽取核心 ----------------------------------------------------- #

def extract_pdf(pdf_path: Path) -> Dict[str, Any]:
    """对单个 PDF 做结构化抽取,产出稳定 JSON 契约。"""
    pages: List[Dict[str, Any]] = []
    with pdfplumber.open(str(pdf_path)) as pdf:
        for idx, page in enumerate(pdf.pages, start=1):
            text = page.extract_text() or ""
            tables_raw = page.extract_tables() or []
            tables: List[Dict[str, Any]] = []
            for t_no, tbl in enumerate(tables_raw, start=1):
                rows = [
                    [(cell or "").strip() for cell in row]
                    for row in tbl
                ]
                tables.append({"table_no": t_no, "rows": rows})
            pages.append({"page_no": idx, "text": text, "tables": tables})
    return {
        "source": str(pdf_path),
        "page_count": len(pages),
        "pages": pages,
    }


def write_output(payload: Dict[str, Any], out_path: Path) -> Path:
    out_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return out_path


# ---------- 样例 PDF 生成(无真实年报时的兜底) -------------------------- #

def make_sample_pdf(out_path: Path) -> Path:
    """用 fpdf2 生成 1 份 2 页"模拟年报"PDF,仅用于流程验证。"""
    from fpdf import FPDF  # 延迟导入,避免 --extract 模式不必要的依赖

    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Page 1: cover + summary ----------------------------------------
    # 用 ASCII-only 内容避开 Helvetica(core font)的中文限制。
    # 真实中文年报场景下,需在 Phase 1 切换到 CID 字体(如 STSong-Light)。
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Company X 2025 Annual Report (Sample)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(
        0, 8,
        _dt.date.today().strftime("Generated: %Y-%m-%d  |  DEMO ONLY - not real data"),
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(
        0, 6,
        "This sample PDF is auto-generated by pdfplumber_demo.py to validate "
        "the PDF-financial-statement extraction flow. Phase 0 does not depend "
        "on real data; once Phase 1 ingests 5-10 real annual reports of "
        "leading companies, the --extract mode will batch-process them.",
    )

    # --- Page 2: sample table (simplified P&L) ---------------------------
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Consolidated Income Statement (FY2025, Demo)",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(220, 220, 220)
    headers = ["Item", "FY2024", "FY2025", "YoY %"]
    widths = [55, 35, 35, 25]
    for w, h in zip(widths, headers):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 10)
    sample_rows = [
        ("Revenue",          "3,521.4", "3,867.5", "+9.8%"),
        ("Cost of Revenue",  "2,432.8", "2,654.2", "+9.1%"),
        ("Gross Profit",     "1,088.6", "1,213.3", "+11.5%"),
        ("R&D Expense",      "192.1",   "215.8",   "+12.3%"),
        ("Net Income",       "361.4",   "412.6",   "+14.2%"),
    ]
    for item, y24, y25, yoy in sample_rows:
        pdf.cell(widths[0], 7, item, border=1)
        pdf.cell(widths[1], 7, y24,  border=1)
        pdf.cell(widths[2], 7, y25,  border=1)
        pdf.cell(widths[3], 7, yoy,  border=1)
        pdf.ln()

    pdf.output(str(out_path))
    return out_path


# ---------- CLI --------------------------------------------------------- #

def _parse_args(argv: List[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="pdfplumber 财报解析 demo · Phase 0 §5 #3",
    )
    p.add_argument(
        "--extract", metavar="PDF_PATH",
        help="抽取指定 PDF(否则走 --make-sample 自生成流程)",
    )
    p.add_argument(
        "--out", metavar="JSON_PATH",
        help="输出 JSON 路径(默认 samples/<src-basename>.extract.json)",
    )
    p.add_argument(
        "--make-sample", action="store_true",
        help="显式声明走自生成样例 PDF 流程(默认行为)",
    )
    return p.parse_args(argv)


def main(argv: List[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)

    if args.extract:
        pdf_path = Path(args.extract).expanduser().resolve()
        if not pdf_path.is_file():
            print(f"[ERR] PDF not found: {pdf_path}", file=sys.stderr)
            return 1
        out = Path(args.out) if args.out else SAMPLES_DIR / f"{pdf_path.stem}.extract.json"
    else:
        # 默认/--make-sample 模式:生成样例 PDF 后抽取
        sample_pdf = SAMPLES_DIR / "_sample-fy2025.pdf"
        make_sample_pdf(sample_pdf)
        print(f"[OK] sample PDF generated: {sample_pdf}")
        pdf_path = sample_pdf
        out = Path(args.out) if args.out else SAMPLES_DIR / "demo-extract.json"

    payload = extract_pdf(pdf_path)
    out_path = write_output(payload, out)

    # 简要统计
    table_total = sum(len(p["tables"]) for p in payload["pages"])
    print(
        f"[OK] extracted {payload['page_count']} pages, "
        f"{table_total} tables -> {out_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
